import BodyWrapper from "@/_libs/components/layouts/BodyWrapper/BodyWrapper";
import HeaderBasic from "@/_libs/components/organisms/headers/HeaderBasic/HeaderBasic";
import type { Metadata } from "next";
import "../_libs/scss/styles.scss";
import { HeaderContexts } from "./_common/contexts/headerContexts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <BodyWrapper>
        <HeaderBasic
          logoImageItem={
            HeaderContexts.logoImageItem
          }
        />
        <main>
          {children}
        </main>
      </BodyWrapper>
    </html>
  );
}
